unpackaged/main/default/objects/Account/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/PDF_Company_Information__mdt/PDF_Company_Information__mdt.object-meta.xml
<CustomObject>
    <label>PDF Company Information</label>
    <pluralLabel>PDF Company Information</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/PDF_Company_Information__mdt/fields/City_State_Zip__c.field-meta.xml
<CustomField>
    <fullName>City_State_Zip__c</fullName>
    <label>City State Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Company_Information__mdt/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Company_Information__mdt/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Company_Information__mdt/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Company_Information__mdt/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <label>Suite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/PDF_Document_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for PDF document generation by object type</description>
    <label>PDF Document Configuration</label>
    <pluralLabel>PDF Document Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/fields/File_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>File_Name_Prefix__c</fullName>
    <label>File Name Prefix</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/fields/Record_Id_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Record_Id_Parameter__c</fullName>
    <description>The URL parameter name used to pass the record ID to the Visualforce page. Default is &#39;id&#39;. Change only if your VF page expects a different parameter name.</description>
    <label>Record Id Parameter</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/fields/Record_Number_Field__c.field-meta.xml
<CustomField>
    <fullName>Record_Number_Field__c</fullName>
    <description>API name of the field containing the record number</description>
    <label>Record Number Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/fields/Template_Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Page_Name__c</fullName>
    <description>The name of the Visualforce page that contains the PDF template (e.g., QuotePDFTemplate). Do not include the .page extension.</description>
    <label>Template Page Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Document_Configuration__mdt/fields/Viewer_Header__c.field-meta.xml
<CustomField>
    <fullName>Viewer_Header__c</fullName>
    <description>The text to display in the header of the PDF viewer modal (e.g., Quote PDF Preview)</description>
    <label>Viewer Header</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/PDF_Viewer_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>PDF Viewer Configuration</label>
    <pluralLabel>PDF Viewer Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Download_Button_Color__c.field-meta.xml
<CustomField>
    <fullName>Download_Button_Color__c</fullName>
    <description>Hex color code for the Download button (e.g., #0070D2)</description>
    <label>Download Button Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Email_Button_Color__c.field-meta.xml
<CustomField>
    <fullName>Email_Button_Color__c</fullName>
    <description>Hex color code for the Email button (e.g., #0070D2)</description>
    <label>Email Button Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/File_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>File_Name_Prefix__c</fullName>
    <description>Prefix used when saving the PDF file</description>
    <label>File Name Prefix</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Save_Button_Color__c.field-meta.xml
<CustomField>
    <fullName>Save_Button_Color__c</fullName>
    <description>Hex color code for the Save button (e.g., #0070D2)</description>
    <label>Save Button Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Show_Cancel_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Cancel_Button__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls visibility of the Cancel button</description>
    <label>Show Cancel Button</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Show_Download_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Download_Button__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls visibility of the Download PDF button</description>
    <label>Show Download Button</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Show_Email_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Email_Button__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls visibility of the Email PDF button</description>
    <label>Show Email Button</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Show_Save_Button__c.field-meta.xml
<CustomField>
    <fullName>Show_Save_Button__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls visibility of the Save PDF button</description>
    <label>Show Save Button</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/PDF_Viewer_Configuration__mdt/fields/Viewer_Header__c.field-meta.xml
<CustomField>
    <fullName>Viewer_Header__c</fullName>
    <description>This is the value you want displayed on the header of the PDF Viewer (ie. &quot;PDF Viewer&quot;)</description>
    <label>Viewer Header</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Bill_to_email__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_email__c</fullName>
    <label>Bill to Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Bill_to_phone__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_phone__c</fullName>
    <label>Bill to Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Quote_Net_Terms__c.field-meta.xml
<CustomField>
    <fullName>Quote_Net_Terms__c</fullName>
    <label>Quote Net Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Terms</fullName>
                <default>true</default>
                <label>No Terms</label>
            </value>
            <value>
                <fullName>Pay on Pay</fullName>
            </value>
            <value>
                <fullName>NET10</fullName>
            </value>
            <value>
                <fullName>NET15</fullName>
            </value>
            <value>
                <fullName>NET20</fullName>
            </value>
            <value>
                <fullName>NET30</fullName>
            </value>
            <value>
                <fullName>NET40</fullName>
            </value>
            <value>
                <fullName>NET45</fullName>
            </value>
            <value>
                <fullName>NET50</fullName>
            </value>
            <value>
                <fullName>NET60</fullName>
            </value>
            <value>
                <fullName>NET75</fullName>
            </value>
            <value>
                <fullName>NET90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Ship_to_email__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_email__c</fullName>
    <label>Ship to email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Ship_to_phone__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_phone__c</fullName>
    <label>Ship to phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>varcpq__Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Amount_GST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_GST__c</fullName>
    <label>Tax Amount GST</label>
    <summarizedField>QuoteLineItem.Tax_Amount_GST__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Amount_HST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_HST__c</fullName>
    <label>Tax Amount HST</label>
    <summarizedField>QuoteLineItem.Tax_Amount_HST__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Amount_PST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_PST__c</fullName>
    <label>Tax Amount PST</label>
    <summarizedField>QuoteLineItem.Tax_Amount_PST__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Amount_QST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_QST__c</fullName>
    <label>Tax Amount QST</label>
    <summarizedField>QuoteLineItem.Tax_Amount_QST__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <formula>varcpq_line_tax_rate__c * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Rate_GST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_GST__c</fullName>
    <label>Tax Rate GST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Rate_HST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_HST__c</fullName>
    <label>Tax Rate HST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Rate_PST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_PST__c</fullName>
    <label>Tax Rate PST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Tax_Rate_QST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_QST__c</fullName>
    <label>Tax Rate QST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Amount_GST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_GST__c</fullName>
    <label>Tax Amount GST</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Amount_HST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_HST__c</fullName>
    <label>Tax Amount HST</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Amount_PST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_PST__c</fullName>
    <label>Tax Amount PST</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Amount_QST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_QST__c</fullName>
    <label>Tax Amount QST</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Rate_GST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_GST__c</fullName>
    <label>Tax Rate GST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Rate_HST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_HST__c</fullName>
    <label>Tax Rate HST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Rate_PST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_PST__c</fullName>
    <label>Tax Rate PST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/QuoteLineItem/fields/Tax_Rate_QST__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_QST__c</fullName>
    <label>Tax Rate QST</label>
    <precision>7</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/PdfViewerController.cls
public with sharing class PdfViewerController {
    @AuraEnabled(cacheable=true)
    public static PDF_Document_Configuration__mdt getDocumentConfiguration(Id recordId) {
        String objectApiName = recordId.getSObjectType().getDescribe().getName();
        
        List<PDF_Document_Configuration__mdt> configs = [
            SELECT Object_API_Name__c, 
            Template_Page_Name__c,
            Viewer_Header__c,
            Record_Id_Parameter__c,
            File_Name_Prefix__c,
            Record_Number_Field__c
            FROM PDF_Document_Configuration__mdt
            WHERE Object_API_Name__c = :objectApiName
            LIMIT 1
        ];
        
        if (configs.isEmpty()) {
            throw new AuraHandledException('No PDF configuration found for: ' + objectApiName);
        }
        
        return configs[0];
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getButtonConfiguration(String objectApiName) {
        List<PDF_Viewer_Configuration__mdt> configs = [
            SELECT Object_API_Name__c, 
            Show_Cancel_Button__c, 
            Show_Save_Button__c,
            Show_Download_Button__c, 
            Show_Email_Button__c, 
            Save_Button_Color__c,
            Download_Button_Color__c,
            Email_Button_Color__c
            FROM PDF_Viewer_Configuration__mdt
            WHERE Object_API_Name__c = :objectApiName
            LIMIT 1
        ];
        
        if (configs.isEmpty()) {
            throw new AuraHandledException('No viewer configuration found for: ' + objectApiName);
        }
        
        PDF_Viewer_Configuration__mdt config = configs[0];
        return new Map<String, Object>{
            'showSave' => config.Show_Save_Button__c,
                'showDownload' => config.Show_Download_Button__c,
                'showEmail' => config.Show_Email_Button__c,
                'showCancel' => config.Show_Cancel_Button__c,
                'saveButtonColor' => config.Save_Button_Color__c,
                'downloadButtonColor' => config.Download_Button_Color__c,
                'emailButtonColor' => config.Email_Button_Color__c
                };
                    }
    
    @AuraEnabled
    public static ContentVersion savePdf(Id recordId) {
        try {
            return BasePDFController.savePDFToRecord(recordId);
        } catch (Exception e) {
            throw new AuraHandledException('Error saving PDF: ' + e.getMessage());
        }
    }
    
    @AuraEnabled (cacheable = true)
    public static List<fieldOption> getFieldOptions(Id recordId){
        List<fieldOption> fields = new List<fieldOption>();
        String objectApiName = recordId.getSObjectType().getDescribe().getName();
        List<Schema.FieldSetMember> fieldSet = new List<Schema.FieldSetMember>();
        if(objectApiName == 'Quote'){
            fieldSet = SObjectType.QuoteLineItem.FieldSets.getMap().get('PDF_Fields_QLI').getFields();
            system.debug(fieldset);
        }
        for(Schema.FieldSetMember fsm : fieldSet){
            fieldOption fo = new fieldOption();
            fo.label = fsm.getLabel();
            fo.value = fsm.getFieldPath();
            fields.add(fo);
        }
        System.debug('fields '+fields);
        return fields;
    }
    
    public class fieldOption{
        @AuraEnabled public string label {get;set;}
        @AuraEnabled public string value {get;set;}
    }
    
	@AuraEnabled
    public static ContentVersion exportCSV(Id recordId) {
        return BasePDFController.saveCSVToRecord(recordId);
    }
    
    
    @AuraEnabled
    public static Map<String, Object> getDataForXlsx(Id recordId){
        Quote quote = [
            SELECT Id, QuoteNumber, Quote_Net_Terms__c, ExpirationDate, CreatedDate,
                   BillingName, ShippingName, Bill_to_email__c, Ship_to_email__c,
                   Bill_to_phone__c, Ship_to_phone__c,
                   Shipping_Method__c, Customer_PO__c, Tax_Rate__c,
                   Account.Name, Account.BillingCountry,
                   Opportunity.Name, Opportunity.Owner.Name, Opportunity.Owner.Email,
                   Contract.Name, BillingAddress, ShippingAddress, Account.RecordType.Name,
                   Tax_Rate_GST__c, Tax_Rate_HST__c, Tax_Rate_PST__c, Tax_Rate_QST__c, Tax_Amount_GST__c, Tax_Amount_HST__c, 
            	   Tax_Amount_PST__c, Tax_Amount_QST__c, CurrencyIsoCode,Tax,
                   AVA_SFCLOUD__ShippingHandling_Tax__c, ShippingHandling
            FROM Quote WHERE Id = :recordId
            LIMIT 1
        ];

        List<QuoteLineItem> items = [
            SELECT Product2.Name, Quantity, UnitPrice, varcpq__EXT_Price__c, 
                   varcpq__Manufacturer__c, Description , varcpq__DH_Quote_Group__r.name
            FROM QuoteLineItem WHERE QuoteId = :recordId
        ];

        // Fetch company info from metadata using RecordType
    String recordTypeName = quote.Account.RecordType.Name;
    List<PDF_Company_Information__mdt> companyInfoList = [
        SELECT Company_Name__c, Street__c, Suite__c, City_State_Zip__c, 
               Phone__c, Website__c, Record_Type__c
        FROM PDF_Company_Information__mdt 
        WHERE Record_Type__c = :recordTypeName
        LIMIT 1
    ];

        Map<String, String> companyInfoMap = new Map<String, String>();
        if (!companyInfoList.isEmpty()) {
            PDF_Company_Information__mdt companyInfo = companyInfoList[0];
            companyInfoMap.put('Company_Name__c', companyInfo.Company_Name__c);
            companyInfoMap.put('Street__c', companyInfo.Street__c);
            companyInfoMap.put('Suite__c', companyInfo.Suite__c);
            companyInfoMap.put('City_State_Zip__c', companyInfo.City_State_Zip__c);
            companyInfoMap.put('Phone__c', companyInfo.Phone__c);
            companyInfoMap.put('Website__c', companyInfo.Website__c);
        }
    
        return new Map<String, Object>{
            'quote' => quote,
            'lineItems' => items,
            'companyInfo' => companyInfoMap
        };
        
    }
    
    @AuraEnabled
    public static void saveExcelFileQuote(String base64Data, String fileName, Id quoteId){
        System.debug('fileName:: ' + fileName);
        System.debug('quoteId:: ' + quoteId);
        
        ContentVersion cv = new ContentVersion();
        cv.VersionData = EncodingUtil.base64Decode(base64Data);
        cv.Title = fileName;
        cv.PathOnClient = fileName;
        
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id = :cv.Id
        ].ContentDocumentId;
        cdl.LinkedEntityId = quoteId;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
    }
    
}