unpackaged/main/default/objects/Manual_Credit_Memo__c/Manual_Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Manual Credit Memo</label>
    <nameField>
        <displayFormat>CRM-{00000}</displayFormat>
        <label>Credit Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Credit_Memo_Type__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Type__c</fullName>
    <label>Credit Memo Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Justification__c.field-meta.xml
<CustomField>
    <fullName>Justification__c</fullName>
    <label>Justification</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Return_Merchandise_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Merchandise_Authorization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Partially Applied</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/Return_Merchandise_Authorization__c.object-meta.xml
<CustomObject>
    <label>Return Merchandise Authorization</label>
    <nameField>
        <displayFormat>RMA-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Merchandise Authorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Return Merchandise Authorization</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost/Damaged</fullName>
            </value>
            <value>
                <fullName>Wrong Item</fullName>
            </value>
            <value>
                <fullName>Customer Error</fullName>
            </value>
            <value>
                <fullName>Defective</fullName>
            </value>
            <value>
                <fullName>Short Ship</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending Supplier Credit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/createSupplierCreditQueueTest.cls
@isTest
public class createSupplierCreditQueueTest {

    @testSetup
    public static void createTestData(){
    Account acc = new Account();
    acc.Name ='Test Account';
    acc.Type = 'Supplier';
    insert acc;
        
    Account accCust = new Account();
    accCust.Name ='Test Account Customer';
    accCust.Type = 'Customer';
    insert accCust;
  
    
    Return_Merchandise_Authorization__c rma = new Return_Merchandise_Authorization__c();
    rma.Account__c = accCust.Id; 
    Insert rma;
        
     Manual_Credit_Memo__c mcm = new Manual_Credit_Memo__c();
     mcm.Credit_Memo_Type__c = 'Supplier';
     mcm.CurrencyIsoCode = 'USD' ;
     mcm.Credit_Amount__c = 10.00;
     mcm.Account__c = acc.Id; 
     mcm.Return_Merchandise_Authorization__c = rma.Id;
     mcm.Reason_Code__c = 'Test Code';
     mcm.Justification__c = 'Test Justification';
     insert mcm;
        
    }
    
    @isTest
    public static void testCreateQueue(){
        List<Manual_Credit_Memo__c> mcm = [SELECT ID, Status__c FROM Manual_Credit_Memo__c];
        mcm[0].Status__c = 'Approved';
        Update mcm;
        
    }
    
    
}