unpackaged/main/default/objects/Manual_Credit_Memo__c/Manual_Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Manual Credit Memo</label>
    <nameField>
        <displayFormat>CRM-{00000}</displayFormat>
        <label>Credit Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Credit_Memo_Type__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Type__c</fullName>
    <label>Credit Memo Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Return_Merchandise_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Merchandise_Authorization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Partially Applied</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/Return_Merchandise_Authorization__c.object-meta.xml
<CustomObject>
    <label>Return Merchandise Authorization</label>
    <nameField>
        <displayFormat>RMA-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Merchandise Authorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Return Merchandise Authorization</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending Supplier Credit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Return Merchandise Authorization (Supplier)</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/Supplier_Credit_Queue__c.object-meta.xml
<CustomObject>
    <label>Supplier Credit Queue</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Supplier Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Credit Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Linked_RMA__c.field-meta.xml
<CustomField>
    <fullName>Linked_RMA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked RMA</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipLabel>Supplier Credit Queue</relationshipLabel>
    <relationshipName>Supplier_Credit_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Credit Queue</relationshipLabel>
    <relationshipName>Supplier_Credit_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Supplier_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manual credit memo of type supplier</description>
    <label>Supplier Credit Memo</label>
    <referenceTo>Manual_Credit_Memo__c</referenceTo>
    <relationshipLabel>Supplier Credit Queue</relationshipLabel>
    <relationshipName>Supplier_Credit_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/createSupplierCreditQueue.cls
public class createSupplierCreditQueue {

    public static void createQueue(List<Manual_Credit_Memo__c>manualCreditMemos,Map<Id,Manual_Credit_Memo__c>mcmOldMap){
      
        List<Supplier_Credit_Queue__c> suppCreditQueue = new List<Supplier_Credit_Queue__c>();
        List<Supplier_Credit_Queue__c> suppCreditQueueExt = [SELECT Id,Supplier_Credit_Memo__c FROM Supplier_Credit_Queue__c WHERE Supplier_Credit_Memo__c
                                                             IN :mcmOldMap.keySet()];
        Map<Id,Id> scmVsScq = new  Map<Id,Id>();
        
        if(!suppCreditQueueExt.isEmpty()){      
         for(Supplier_Credit_Queue__c scqExt : suppCreditQueueExt){
           scmVsScq.put(scqExt.Supplier_Credit_Memo__c,scqExt.Id);
         }
        }
        
        for(Manual_Credit_Memo__c mcm : manualCreditMemos){
            
            if(mcm.Return_Merchandise_Authorization__c != null && mcm.Status__c == 'Approved' && mcm.Credit_Memo_Type__c == 'Supplier'){
                    if(scmVsScq.containsKey(mcm.Id)){
                        continue;
                    }    
               Supplier_Credit_Queue__c scq = new Supplier_Credit_Queue__c();
                scq.Linked_RMA__c = mcm.Return_Merchandise_Authorization__c;
                scq.Status__c = 'Open';
                scq.CurrencyIsoCode = mcm.CurrencyIsoCode; 
                scq.Supplier__c = mcm.Account__c;
                scq.Supplier_Credit_Memo__c = mcm.Id;
                scq.Credit_Amount__c = mcm.Credit_Amount__c;
                suppCreditQueue.add(scq);
            }
        }
        
        if(!suppCreditQueue.isEmpty()){
            INSERT suppCreditQueue;
        }
    }
}