unpackaged/main/default/objects/Manual_Credit_Memo__c/Manual_Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Manual Credit Memo</label>
    <nameField>
        <displayFormat>CRM-{00000}</displayFormat>
        <label>Credit Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Bill_Only_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Bill_Only_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill Only Indicator</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Invoice_Reference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Reference</label>
    <referenceTo>varcpq__Invoice__c</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Justification__c.field-meta.xml
<CustomField>
    <fullName>Justification__c</fullName>
    <label>Justification</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Original_Owner__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Return_Merchandise_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Merchandise_Authorization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipLabel>Manual Credit Memo</relationshipLabel>
    <relationshipName>Manual_Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Partially Applied</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/Manual_Credit_Memo_Field_History__c.object-meta.xml
<CustomObject>
    <label>Manual Credit Memo Field History</label>
    <nameField>
        <label>Manual Credit Memo Field History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manual Credit Memo Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/Change_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Change_Timestamp__c</fullName>
    <description>When the field change was made</description>
    <label>Change Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who made the change</description>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manual_Credit_Memo_Field_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>API name of the field that changed</description>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/Manual_Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Manual_Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to Manual Credit Memo record</description>
    <label>Manual Credit Memo</label>
    <referenceTo>Manual_Credit_Memo__c</referenceTo>
    <relationshipLabel>Manual Credit Memo Field Histories</relationshipLabel>
    <relationshipName>Manual_Credit_Memo_Field_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <description>Updated value of the field</description>
    <label>New Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Manual_Credit_Memo_Field_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <description>Previous value of the field</description>
    <label>Old Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/Return_Merchandise_Authorization__c.object-meta.xml
<CustomObject>
    <label>Return Merchandise Authorization</label>
    <nameField>
        <displayFormat>RMA-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Merchandise Authorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Return Merchandise Authorization</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Original_Owner__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Return_Merchandise_Authorization1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost/Damaged</fullName>
            </value>
            <value>
                <fullName>Wrong Item</fullName>
            </value>
            <value>
                <fullName>Customer Error</fullName>
            </value>
            <value>
                <fullName>Defective</fullName>
            </value>
            <value>
                <fullName>Short Ship</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending Supplier Credit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization_Line_It__c/Return_Merchandise_Authorization_Line_It__c.object-meta.xml
<CustomObject>
    <label>RMA Line Item</label>
    <nameField>
        <displayFormat>RMALI-{00000}</displayFormat>
        <label>Return Merchandise Authorization Line It</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Return_Merchandise_Authorization_Line_It__c/fields/Credit_Memo_Applied__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Applied__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Credit Memo Applied</label>
    <referenceTo>Manual_Credit_Memo__c</referenceTo>
    <relationshipLabel>RMA Line Item</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization_Line_It</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization_Line_It__c/fields/Return_Merchandise_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Return_Merchandise_Authorization__c</fullName>
    <label>RMA (Parent)</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipName>Return_Merchandise_Authorization_Line_It</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization_Line_It__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ManualCreditMemoTriggerHandler.cls
public class ManualCreditMemoTriggerHandler {
    
    public static void createCreditMemoHistoryRecords(Map<Id, Manual_Credit_Memo__c> oldMap,List<Manual_Credit_Memo__c> newList)
    {
        
        List<Manual_Credit_Memo_Field_History__c> historyRecords = new List<Manual_Credit_Memo_Field_History__c>();
        
        for (Manual_Credit_Memo__c newRec : newList) 
        {
            Manual_Credit_Memo__c oldRec = oldMap.get(newRec.Id);
            
            
            compareValues(historyRecords, newRec.Id, 'Account__c', oldRec.Account__c, newRec.Account__c);
            compareValues(historyRecords, newRec.Id, 'Bill_Only_Indicator__c', oldRec.Bill_Only_Indicator__c, newRec.Bill_Only_Indicator__c);
            compareValues(historyRecords, newRec.Id, 'CreatedById', oldRec.CreatedById, newRec.CreatedById);
            compareValues(historyRecords, newRec.Id, 'Credit_Amount__c', oldRec.Credit_Amount__c, newRec.Credit_Amount__c);
            compareValues(historyRecords, newRec.Id, 'CurrencyIsoCode', oldRec.CurrencyIsoCode, newRec.CurrencyIsoCode);
            compareValues(historyRecords, newRec.Id, 'Invoice_Reference__c', oldRec.Invoice_Reference__c, newRec.Invoice_Reference__c);
            compareValues(historyRecords, newRec.Id, 'Justification__c', oldRec.Justification__c, newRec.Justification__c);
            compareValues(historyRecords, newRec.Id, 'LastModifiedById', oldRec.LastModifiedById, newRec.LastModifiedById);
            compareValues(historyRecords, newRec.Id, 'Original_Owner__c', oldRec.Original_Owner__c, newRec.Original_Owner__c);
            compareValues(historyRecords, newRec.Id, 'OwnerId', oldRec.OwnerId, newRec.OwnerId);
            compareValues(historyRecords, newRec.Id, 'Reason_Code__c', oldRec.Reason_Code__c, newRec.Reason_Code__c);
            compareValues(historyRecords, newRec.Id, 'Status__c', oldRec.Status__c, newRec.Status__c);
            
          
        }
        
        if (!historyRecords.isEmpty()) {
            insert historyRecords;
              System.debug('Insert completed successfully for ' + historyRecords.size() +historyRecords);
        }
         else {
            System.debug('No changes detected, no history records to insert.');
        }
    }
    
    private static void compareValues(List<Manual_Credit_Memo_Field_History__c> historyRecords,
                                      Id parentId, String fieldName,
                                      Object oldVal, Object newVal) 
    {
        if (oldVal != newVal && (oldVal == null || !oldVal.equals(newVal))) 
        {
             System.debug(' Change detected for field: ' + fieldName + ' | Old Value: ' + oldVal +' | New Value: ' + newVal);
            
            historyRecords.add(new Manual_Credit_Memo_Field_History__c(
                Manual_Credit_Memo__c = parentId,
                Field_Name__c = fieldName,
                Old_Value__c = String.valueOf(oldVal),
                New_Value__c = String.valueOf(newVal),
                Changed_By__c = UserInfo.getUserId(),
                Change_Timestamp__c = System.now()
            ));
        }
        
    }
    
    public static void createRMALineItem(List<Manual_Credit_Memo__c> manualCreditMemo){
        System.debug('manualCreditMemo: ' + manualCreditMemo);
        //List<Return_Merchandise_Authorization_Line_It__c> insertRMALineItem = new List<Return_Merchandise_Authorization_Line_It__c>();
        
        // Collect all RMA Ids from incoming Credit Memos
        Set<Id> rmaIds = new Set<Id>();
        for (Manual_Credit_Memo__c mcc : manualCreditMemo) {
            if (mcc.Return_Merchandise_Authorization__c != null) {
                rmaIds.add(mcc.Return_Merchandise_Authorization__c);
            }
        }
    
        if (rmaIds.isEmpty()) {
            System.debug('No RMAs found on Credit Memos');
            return;
        }
    
        // Query existing RMA Line Items for those RMAs
        List<Return_Merchandise_Authorization_Line_It__c> rmaLineItems = [
            SELECT Id, Return_Merchandise_Authorization__c, Credit_Memo_Applied__c
            FROM Return_Merchandise_Authorization_Line_It__c
            WHERE Return_Merchandise_Authorization__c IN :rmaIds
        ];
    
        System.debug('Fetched RMA Line Items: ' + rmaLineItems);
    
        // Build a map of RMA Id -> Credit Memo Id (assumes 1:1)
        Map<Id, Id> rmaToCreditMemoMap = new Map<Id, Id>();
        for (Manual_Credit_Memo__c mcc : manualCreditMemo) {
            if (mcc.Return_Merchandise_Authorization__c != null) {
                rmaToCreditMemoMap.put(mcc.Return_Merchandise_Authorization__c, mcc.Id);
            }
        }
    
        // Update each RMA Line Item to reference its Credit Memo
        List<Return_Merchandise_Authorization_Line_It__c> updates = new List<Return_Merchandise_Authorization_Line_It__c>();
        for (Return_Merchandise_Authorization_Line_It__c lineItem : rmaLineItems) {
            Id creditMemoId = rmaToCreditMemoMap.get(lineItem.Return_Merchandise_Authorization__c);
            if (creditMemoId != null) {
                lineItem.Credit_Memo_Applied__c = creditMemoId;
                updates.add(lineItem);
            }
        }
    
        if (!updates.isEmpty()) {
            update updates;
            System.debug('Updated RMA Line Items with Credit Memo: ' + updates);
        }
        /*for(Manual_Credit_Memo__c mcc: manualCreditMemo){
            Return_Merchandise_Authorization_Line_It__c RMALineItem = new Return_Merchandise_Authorization_Line_It__c();
            
            RMALineItem.Credit_Memo_Applied__c = mcc.Id;
            RMALineItem.Return_Merchandise_Authorization__c = mcc.Return_Merchandise_Authorization__c;
            
            System.debug('RMALineItem: ' + RMALineItem);
            
            //insert RMALineItem;
        }*/
    }
}