unpackaged/main/default/objects/Return_Merchandise_Authorization__c/Return_Merchandise_Authorization__c.object-meta.xml
<CustomObject>
    <label>Return Merchandise Authorization</label>
    <nameField>
        <displayFormat>RMA-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Merchandise Authorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending Supplier Credit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Return_Merchandise_Authorization__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Return Merchandise Authorization (Supplier)</relationshipLabel>
    <relationshipName>Return_Merchandise_Authorization1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/Supplier_Credit_Queue__c.object-meta.xml
<CustomObject>
    <label>Supplier Credit Queue</label>
    <nameField>
        <displayFormat>SQ-{00000}</displayFormat>
        <label>Supplier Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Credit Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Linked_RMA__c.field-meta.xml
<CustomField>
    <fullName>Linked_RMA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked RMA</label>
    <referenceTo>Return_Merchandise_Authorization__c</referenceTo>
    <relationshipLabel>Supplier Credit Queue</relationshipLabel>
    <relationshipName>Supplier_Credit_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Credit Queue</relationshipLabel>
    <relationshipName>Supplier_Credit_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Timestamp_Processed__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Processed__c</fullName>
    <label>Timestamp: Processed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Queue__c/fields/Timestamp_Received__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Received__c</fullName>
    <label>Timestamp: Received</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/searchSupplierCreditQueueTest.cls
@isTest
public class searchSupplierCreditQueueTest {

    @testSetup
    public static void createData(){
        
     Datetime dt = Datetime.now();
    Account acc = new Account();
    acc.Name ='Test Account';
    acc.Type = 'Supplier';
    insert acc;
        
    Return_Merchandise_Authorization__c rma = new Return_Merchandise_Authorization__c();
       rma.Status__c = 'Approved'; 
       insert rma;
        
       Supplier_Credit_Queue__c scq = new Supplier_Credit_Queue__c();
       scq.Status__c = 'Open';
       scq.Linked_RMA__c = rma.Id;
       scq.Supplier__c = acc.Id;
       scq.Timestamp_Processed__c= dt;
        scq.Timestamp_Received__c = dt;
        insert scq; 
        
        Supplier_Credit_Queue__c scq1 = new Supplier_Credit_Queue__c();
       scq1.Status__c = 'Open';
       scq1.Linked_RMA__c = rma.Id;
       scq1.Supplier__c = acc.Id;
       scq1.Timestamp_Processed__c= dt;
       scq1.Timestamp_Received__c = dt;
       insert scq1;
    }
    
    @isTest
    public static void creditques(){
        
        List<Supplier_Credit_Queue__c> scQueue = [Select Id,Name,Status__c,Supplier__c,CurrencyIsoCode,Linked_RMA__c
                                                  ,Timestamp_Processed__c,Timestamp_Received__c from Supplier_Credit_Queue__c order By Id ASC];
        
 
        string currentUserId = UserInfo.getUserId();
        String supplierId = String.valueOf(scQueue[0].Supplier__c);
        string rmaId = String.valueOf(scQueue[0].Linked_RMA__c);
        List<Id>scqList = new List<Id>();
        scqList.add(scQueue[0].Id);
        Test.startTest();
        searchSupplierCreditQueueHandler.creditQueues('Test Account',scQueue[0].Name,supplierId,scQueue[0].Status__c,rmaId,
                                                    scQueue[0].CurrencyIsoCode,currentUserId,scQueue[0].Timestamp_Processed__c,
                                                    scQueue[0].Timestamp_Received__c);
        
        /*searchSupplierCreditQueueHandler.loadMoreData(scQueue[0].Id,'Test Account',scQueue[0].Name,supplierId,scQueue[0].Status__c,rmaId,
                                                    scQueue[0].CurrencyIsoCode,currentUserId,scQueue[0].Timestamp_Processed__c,
                                                    scQueue[0].Timestamp_Received__c);*/
        
        searchSupplierCreditQueueHandler.updateStatus(scqList, 'Applied');
        Test.stopTest();
    }
    
    
    
}